/**
 * Tour Data - Complete tour packages with details, images, and pricing
 */

export interface TourImage {
  src: string;
  alt: string;
}

export interface Tour {
  id: string;
  title: string;
  description: string;
  shortDescription: string;
  heroImage: string;
  images: TourImage[];
  activities: string[];
  packageIncludes: string[];
  packageExcludes?: string[];
  pickupTime: string;
  duration: string;
  groupSize: string;
  difficulty: string;
  highlights: string[];
  itinerary: string;
  pricePerPerson: number;
  currency: string;
  seasonalNote?: string;
  paymentTerms?: string;
  cancellationPolicy?: string;
}

export const tours: Tour[] = [
  {
    id: 'chiang-rai-one-day-golden-triangle',
    title: 'Chiang Rai One Day & Golden Triangle',
    description: 'Explore Chiang Rai\'s most iconic temples including the stunning White Temple and Blue Temple. Visit the famous Golden Triangle where Thailand, Laos, and Myanmar meet. Experience hot springs, local culture, and boat trips along the Mae Khong River.',
    shortDescription: 'Explore Chiang Rai temples and the Golden Triangle border region',
    heroImage: '/images/generated-white-temple-1.webp',
    images: [
      { src: '/images/generated-white-temple-1.webp', alt: 'Wat Rong Khun White Temple with ornate architecture' },
      { src: '/images/generated-white-temple-2.webp', alt: 'White Temple intricate details and mirror mosaics' },
      { src: '/images/real-chiang-rai-blue-temple-interior.jpg', alt: 'Blue Temple stunning interior with Buddha' },
      { src: '/images/real-chiang-rai-blue-temple-exterior.jpg', alt: 'Customer at Blue Temple with elephant statues' },
      { src: '/images/real-chiang-rai-black-house-group.jpg', alt: 'Tour group at Black House Museum' },
      { src: '/images/chiang-rai-boat-tour.webp', alt: 'Boat trip on Mae Khong River at Golden Triangle' },
      { src: '/images/chiang-rai-boat-tour.webp', alt: 'Group tour on boat at Mekong River Golden Triangle' },
      { src: '/images/chiang-rai-karen-village.webp', alt: 'Long Neck Karen village visit with colorful textiles' },
      { src: '/images/chiang-rai-karen-girls.webp', alt: 'Long Neck Karen girls in traditional dress' },
    ],
    activities: [
      'Hot Spring',
      'White Temple',
      'Blue Temple',
      'Black Museum',
      'Karen Long Neck Village',
      'Golden Triangle',
      'Boat Trip Along Mae Khong River',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '07:00 - 07:30 AM',
    duration: '10-11 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy',
    highlights: [
      'Visit the famous White Temple with intricate white architecture',
      'Explore the Blue Temple with stunning blue interior',
      'Relax in natural hot springs',
      'Visit the unique Black Museum',
      'Experience Karen Long Neck Village culture',
      'Stand at the Golden Triangle where three countries meet',
      'Boat trip along the Mae Khong River',
    ],
    itinerary: 'Early morning pickup from hotel. Drive to Chiang Rai (about 3 hours). Visit hot springs, White Temple, Blue Temple, and Black Museum. Lunch included. Afternoon visit to Karen Long Neck Village and Golden Triangle. Boat trip on Mae Khong River. Return to Chiang Mai by evening.',
    pricePerPerson: 1700,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'chiang-rai-lalita-cafe',
    title: 'Chiang Rai One Day & Lalita Cafe',
    description: 'Explore Chiang Rai\'s most beautiful temples including the White Temple, Blue Temple, and Red Temple. Visit the Instagram-famous Lalita Cafe with its enchanting garden and waterfall. Experience hot springs and optional Karen Long Neck Village visit.',
    shortDescription: 'Visit White, Blue, Red Temples and Lalita Cafe with stunning gardens',
    heroImage: '/images/1000016220.webp',
    images: [
      { src: '/images/1000016220.webp', alt: 'Wat Rong Khun White Temple with bridge of rebirth' },
      { src: '/images/1000016222.webp', alt: 'Blue Temple with intricate blue and gold architecture' },
      { src: '/images/1000016208.webp', alt: 'Wat Huay Pla Kang with giant white Guan Yin statue and dragon' },
      { src: '/images/1000016210.webp', alt: 'Wat Huay Pla Kang white Guan Yin Buddha statue' },
      { src: '/images/1000016213.webp', alt: 'Lalita Cafe enchanted garden with waterfall and colorful stepping stones' },
      { src: '/images/1000016216.webp', alt: 'Lalita Cafe waterfall and orchid garden with mist' },
    ],
    activities: [
      'Hot Spring',
      'White Temple',
      'Blue Temple',
      'Red Temple',
      'Lalita Cafe',
      'Optional: Karen Long Neck Village',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '07:00 - 07:30 AM',
    duration: '8-9 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy',
    highlights: [
      'Visit the famous White Temple with intricate white architecture',
      'Explore the Blue Temple with stunning blue and gold interior',
      'Discover the unique Red Temple',
      'Relax in natural hot springs',
      'Experience the magical Lalita Cafe with enchanted garden and waterfall',
      'Optional visit to Karen Long Neck Village',
    ],
    itinerary: 'Early morning pickup from hotel. Drive to Chiang Rai (about 3 hours). Visit hot springs, White Temple, Blue Temple, and Red Temple. Enjoy lunch. Afternoon visit to Lalita Cafe with its beautiful garden and waterfall. Optional stop at Karen Long Neck Village. Return to Chiang Mai by evening.',
    pricePerPerson: 1300,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks at Lalita Cafe', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'chiang-rai-one-day',
    title: 'Chiang Rai One Day',
    description: 'Discover the charm of Chiang Rai with its famous temples and cultural sites. Visit the White Temple, Blue Temple, Black Museum, and hot springs. Experience local culture and enjoy optional visits to Karen Long Neck Village.',
    shortDescription: 'Full day exploration of Chiang Rai\'s temples and cultural attractions',
    heroImage: '/images/tour-chiang-rai-one-day-banner.jpg',
    images: [
      { src: '/images/generated-white-temple-1.webp', alt: 'Wat Rong Khun White Temple with ornate architecture' },
      { src: '/images/generated-white-temple-2.webp', alt: 'White Temple intricate details and mirror mosaics' },
      { src: '/images/real-chiang-rai-blue-temple-interior.jpg', alt: 'Blue Temple stunning interior with Buddha' },
      { src: '/images/real-chiang-rai-blue-temple-exterior.jpg', alt: 'Customer at Blue Temple with elephant statues' },
      { src: '/images/real-chiang-rai-black-house-group.jpg', alt: 'Tour group at Black House Museum' },
      { src: '/images/chiang-rai-karen-village.webp', alt: 'Long Neck Karen village visit with colorful textiles' },
      { src: '/images/chiang-rai-karen-girls.webp', alt: 'Long Neck Karen girls in traditional dress' },
    ],
    activities: [
      'Hot Spring',
      'White Temple',
      'Blue Temple',
      'Black Museum',
      'Optional: Karen Long Neck Village',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '07:00 - 07:30 AM',
    duration: '8-9 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy',
    highlights: [
      'Visit the iconic White Temple with its unique architecture',
      'Explore the serene Blue Temple',
      'Experience the quirky Black Museum',
      'Relax in natural hot springs',
      'Optional cultural village visits',
    ],
    itinerary: 'Morning pickup from hotel. Drive to Chiang Rai. Visit hot springs, White Temple, Blue Temple, and Black Museum. Lunch included. Optional visit to Karen Long Neck Village. Return to Chiang Mai by evening.',
    pricePerPerson: 1300,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'doi-inthanon-national-park',
    title: 'Doi Inthanon National Park',
    description: 'Explore Thailand\'s highest mountain with visits to the King\'s and Queen\'s Pagodas, Hmong Market, White Karen Village, and two stunning waterfalls - Wachirathan and Sirithan. Experience the best of Doi Inthanon in one comprehensive tour.',
    shortDescription: 'Full day tour including both Wachirathan and Sirithan waterfalls',
    heroImage: '/images/tour-doi-inthanon-banner.jpg',
    images: [
      { src: '/images/real-doi-inthanon-1.jpg', alt: 'Group at highest spot in Thailand sign' },
      { src: '/images/real-doi-inthanon-2.jpg', alt: 'King and Queen Pagodas with gardens' },
      { src: '/images/doi-inthanon-king-queen-pagodas.webp', alt: 'King and Queen Pagodas with colorful flower gardens' },
      { src: '/images/doi-inthanon-wachirathan-waterfall.webp', alt: 'Wachirathan Waterfall in Doi Inthanon National Park' },
      { src: '/images/doi-inthanon-hmong-market.webp', alt: 'Tourists shopping at Hmong Market on Doi Inthanon' },
    ],
    activities: [
      'The Highest Spot in Thailand',
      'King\'s and Queen\'s Pagoda',
      'Hmong Market',
      'White Karen Village',
      'Wachirathan Waterfall',
      'Sirithan Waterfall',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '08:00 - 08:30 AM',
    duration: '8-9 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy to Moderate',
    highlights: [
      'Visit Thailand\'s highest mountain peak at 2,565 meters',
      'Explore sacred King\'s and Queen\'s Pagodas with stunning views',
      'Experience authentic Hmong culture and local markets',
      'Visit White Karen Village and learn about local traditions',
      'See two magnificent waterfalls - Wachirathan and Sirithan',
    ],
    itinerary: 'Morning pickup from hotel (08:00-08:30 AM). Drive to Doi Inthanon National Park. Visit the highest spot in Thailand with panoramic mountain views. Explore the King\'s and Queen\'s Pagodas. Visit Hmong Market for local crafts and products. Stop at White Karen Village. Visit Wachirathan Waterfall and Sirithan Waterfall. Lunch included. Return to hotel by evening.',
    pricePerPerson: 1500,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'doi-inthanon-trek-pha-dok-siew',
    title: 'Doi Inthanon National Park - Trek Pha Dok Siew',
    description: 'Experience the highest spot in Thailand with stunning mountain views, ancient temples, and nature trails. Visit the King\'s and Queen\'s Pagodas, explore local Hmong markets, and trek through the beautiful Pha Dok Siew nature trail.',
    shortDescription: 'Trek through Thailand\'s highest mountain with temple visits and waterfall exploration',
    heroImage: '/images/tour-pha-dok-siew-banner.jpg',
    images: [
      { src: '/images/real-pha-dok-siew-1.jpg', alt: 'Tour group at Pha Dok Siew waterfall trail' },
      { src: '/images/real-pha-dok-siew-waterfall-1.jpg', alt: 'Customer at waterfall with bamboo platform' },
      { src: '/images/real-pha-dok-siew-waterfall-2.jpg', alt: 'Tour group viewing spectacular waterfall' },
    ],
    activities: [
      'The Highest Spot in Thailand',
      'King\'s and Queen\'s Pagoda',
      'Hmong Market',
      'White Karen Village',
      'Wachirathan Waterfall',
      '2 hrs Trek Pha Dok Siew Nature Trail',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '07:00 - 07:30 AM',
    duration: '8-9 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Moderate',
    highlights: [
      'Visit Thailand\'s highest mountain peak at 2,565 meters',
      'Explore sacred King\'s and Queen\'s Pagodas with panoramic views',
      'Experience authentic Hmong culture and local markets',
      'Trek through pristine nature trails with waterfalls',
      'Visit White Karen Village to learn about local traditions',
    ],
    itinerary: 'Start early morning pickup from your hotel. Drive to Doi Inthanon National Park, visiting the highest point with stunning views. Explore the King\'s and Queen\'s Pagodas, visit the Hmong Market, and trek through the Pha Dok Siew nature trail. Stop at Wachirathan Waterfall and White Karen Village. Lunch included. Return to hotel by evening.',
    pricePerPerson: 1500,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'doi-inthanon-trek-kew-mae-pan',
    title: 'Doi Inthanon National Park - Trek Kew Mae Pan',
    description: 'Experience the highest mountain in Thailand with the scenic Kew Mae Pan nature trail. Visit the King\'s and Queen\'s Pagodas, explore local markets, and trek through pristine forests with panoramic mountain views. Available November to May.',
    shortDescription: 'Trek the scenic Kew Mae Pan trail on Thailand\'s highest mountain',
    heroImage: '/images/tour-kew-mae-pan-banner.jpg',
    images: [
      { src: '/images/real-kew-mae-pan-1.jpg', alt: 'Tour group at Kew Mae Pan entrance' },
      { src: '/images/real-kew-mae-pan-2.jpg', alt: 'Mountain viewpoint with visitors' },
      { src: '/images/kew-mae-pan-king-queen-pagodas.webp', alt: 'King and Queen Pagodas at sunrise with mountain views' },
      { src: '/images/kew-mae-pan-wachirathan-rainbow.webp', alt: 'Wachirathan Waterfall with beautiful rainbow' },
    ],
    activities: [
      'The Highest Spot in Thailand',
      'King\'s and Queen\'s Pagoda',
      'Hmong Market',
      'White Karen Village',
      'Wachirathan Waterfall',
      '2 hrs Trek Kew Mae Pan Nature Trail',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '07:00 - 07:30 AM',
    duration: '8-9 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Moderate',
    highlights: [
      'Trek the scenic Kew Mae Pan nature trail',
      'Visit Thailand\'s highest mountain peak',
      'Explore sacred King\'s and Queen\'s Pagodas',
      'Experience authentic Hmong culture',
      'Visit White Karen Village',
      'See Wachirathan Waterfall',
      'Enjoy panoramic mountain views',
    ],
    itinerary: 'Early morning pickup from hotel. Drive to Doi Inthanon National Park. Visit the highest point with panoramic views. Trek the Kew Mae Pan nature trail (2 hours). Visit King\'s and Queen\'s Pagodas, Hmong Market, and White Karen Village. Lunch included. Return to hotel by evening.',
    pricePerPerson: 1500,
    currency: 'THB',
    seasonalNote: 'Available November 1 - May 31',
  },
  {
    id: 'one-day-trek-elephant-care',
    title: 'One Day Trek & Elephant Care',
    description: 'Spend a day with rescued elephants in their natural habitat. Trek through lush forests, interact with elephants, enjoy bamboo rafting, and visit beautiful waterfalls. An ethical and memorable experience with proper animal care.',
    shortDescription: 'Trek and interact with elephants, bamboo rafting, and waterfall exploration',
    heroImage: '/images/tour-elephant-banner.jpg',
    images: [
      { src: '/images/real-elephant-feeding.jpg', alt: 'Feeding elephants in sanctuary' },
      { src: '/images/real-elephant-bathing.jpg', alt: 'Elephant bathing in river' },
      { src: '/images/real-elephant-group.jpg', alt: 'Group experience with elephants' },
      { src: '/images/real-elephant-rafting.jpg', alt: 'Bamboo rafting adventure' },
    ],
    activities: [
      'Elephant Care',
      'Trekking About 1 Hour',
      'Mae Wang Water Fall',
      'Bamboo Rafting',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch',
    ],
    pickupTime: '08:00 - 08:30 AM',
    duration: '8-9 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy to Moderate',
    highlights: [
      'Ethical elephant interaction and care experience',
      'Trek through pristine jungle forests',
      'Visit Mae Wang Waterfall',
      'Bamboo rafting on scenic river',
      'Learn about elephant conservation',
    ],
    itinerary: 'Morning pickup from hotel. Travel to elephant sanctuary for hands-on care experience. Trek through forest for about 1 hour. Visit Mae Wang Waterfall for swimming and relaxation. Enjoy bamboo rafting on the river. Lunch included. Return to hotel by evening.',
    pricePerPerson: 1800,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'doi-suthep-temple-hmong-village',
    title: 'Doi Suthep Temple & Hmong Village',
    description: 'Visit the most famous temple in Northern Thailand perched on a mountain. Explore the sacred Doi Suthep temple with 306 steps flanked by mythical Nagas, enjoy panoramic city views, and visit authentic Hmong villages with local crafts.',
    shortDescription: 'Visit iconic Doi Suthep temple and explore authentic Hmong mountain villages',
    heroImage: '/images/tour-doi-suthep-banner.jpg',
    images: [
      { src: '/images/generated-doi-suthep-1.webp', alt: 'Doi Suthep Temple golden pagoda at sunset with city views' },
      { src: '/images/doi-suthep-naga-staircase.webp', alt: 'Tourists climbing the 306-step Naga staircase to Doi Suthep Temple' },
    ],
    activities: [
      'Doi Suthep Temple',
      'Hmong Village Market',
      'Local Craft Shops',
      'Panoramic City Views',
    ],
    packageIncludes: [
      'Transportation',
      'Tourist Guide',
      'Entrance Ticket',
      'Accident Insurance',
    ],
    pickupTime: '08:00 - 08:30 AM',
    duration: '6-7 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy',
    highlights: [
      'Visit the most sacred temple in Northern Thailand',
      'Climb 306 steps flanked by mythical Naga balustrades',
      'Enjoy spectacular panoramic views of Chiang Mai city',
      'Explore authentic Hmong village culture and crafts',
      'Shop for traditional textiles and handicrafts',
    ],
    itinerary: 'Morning pickup from hotel. Drive to Doi Suthep Temple and climb the 306 steps to the golden pagoda. Explore the temple grounds and enjoy city views. Explore Hmong village markets and craft shops. Return to hotel by evening.',
    pricePerPerson: 900,
    currency: 'THB',
  },
  {
    id: 'dan-thewada-wat-baan-den-sticky-waterfall',
    title: 'Dan Thewada - Wat Baan Den - Sticky Waterfall',
    description: 'Discover the beautiful of Chiang Mai\'s most enchanting nature spots in one day. Visit the dreamy Dan Thewada Land of Angel Waterfall Park, explore the stunning Wat Baan Den temple complex, and climb the unique Sticky Waterfall where you can enjoy a refreshing jungle waterfall climbing adventure.',
    shortDescription: 'Explore Dan Thewada waterfall park, Wat Baan Den temple, and climb Sticky Waterfall',
    heroImage: '/images/1000016246.webp',
    images: [
      { src: '/images/1000016246.webp', alt: 'Dan Thewada Land of Angel Waterfall Park with beautiful cascades' },
      { src: '/images/1000016244.webp', alt: 'Wat Baan Den colorful temple complex' },
      { src: '/images/1000016260.webp', alt: 'Sticky Waterfall unique limestone cascade' },
      { src: '/images/1000016257.webp', alt: 'Climbing the Sticky Waterfall barefoot' },
      { src: '/images/1000016254.webp', alt: 'Dan Thewada waterfall surrounded by lush jungle' },
      { src: '/images/1000016251.webp', alt: 'Wat Baan Den temple architecture' },
      { src: '/images/1000016248.webp', alt: 'Refreshing jungle waterfall experience' },
    ],
    activities: [
      'Dan Thewada Land of Angel Waterfall Park',
      'Wat Baan Den',
      'Sticky Waterfall',
    ],
    packageIncludes: [
      'Transportation',
      'Entrance Ticket',
      'Accident Insurance',
      'Lunch (Pad Thai)',
    ],
    pickupTime: '08:30 - 09:00 AM',
    duration: '7-8 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy to Moderate',
    highlights: [
      'Visit the dreamy Dan Thewada waterfall park with enchanting cascades',
      'Explore the colorful Wat Baan Den temple complex',
      'Climb the unique Sticky Waterfall barefoot',
      'Enjoy refreshing jungle waterfall swimming',
      'Experience nature\'s beauty in one day',
    ],
    itinerary: 'Morning pickup from hotel (08:30-09:00 AM). Drive to Dan Thewada Land of Angel Waterfall Park to explore beautiful cascades and jungle scenery. Visit the colorful Wat Baan Den temple complex. Enjoy Pad Thai lunch. Afternoon adventure at Sticky Waterfall where you can climb the unique limestone cascade barefoot. Return to Chiang Mai by evening.',
    pricePerPerson: 1200,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Drinks and snacks', 'Optional activities'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'king-kong-zipline-adventure',
    title: 'King Kong Zipline Adventure',
    description: 'Experience the thrill of flying through the jungle canopy with King Kong Zipline. Choose between Ultimate Program (1,900 THB) with 19 platforms and 9 ziplines, or Extreme Program (2,500 THB) with 11 platforms and 11 ziplines including the longest 1,200m zipline. Enjoy sky bridges, spiral staircases, and nature trail walkways in a safe and exciting environment.',
    shortDescription: 'Fly through jungle canopy with ziplines, sky bridges, and spiral staircases',
    heroImage: '/images/zipline-adventure-cover.webp',
    images: [
      { src: '/images/zipline-adventure-cover.webp', alt: 'Thrilling zipline adventure through jungle canopy' },
      { src: '/images/1000016263.webp', alt: 'King Kong Zipline program pricing and details' },
      { src: '/images/1000016266.webp', alt: 'Zipline adventure pickup times and what to bring' },
    ],
    activities: [
      'Zipline Adventure (9-11 ziplines depending on program)',
      'Sky Bridge Crossing',
      'Spiral Staircase',
      'Nature Trail Walkway',
      'Abseiling',
      'Glass Bridge',
    ],
    packageIncludes: [
      'Round-trip Transfer',
      'Thai Buffet Lunch',
      'New Gloves',
      'Drinking Water',
      'Accident Insurance',
    ],
    pickupTime: '07:00-07:30 AM, 09:00-09:30 AM, 12:00-12:30 PM, or 01:00-01:30 PM',
    duration: '4-5 hours',
    groupSize: 'Small groups',
    difficulty: 'Moderate',
    highlights: [
      'Ultimate Program: 19 platforms, 9 ziplines (400m, 500m, 700m) - 1,900 THB',
      'Extreme Program: 11 platforms, 11 ziplines including longest 1,200m - 2,500 THB',
      'Sky bridges, glass bridge, and spiral staircases',
      'Abseiling and climbing net adventures',
      'Nature trail walkway through jungle',
      'Professional safety equipment and guides',
    ],
    itinerary: 'Pickup from hotel at selected time. Transfer to King Kong Zipline base camp. Safety briefing and equipment fitting. Experience thrilling ziplines, sky bridges, spiral staircases, and nature trails. Enjoy Thai buffet lunch. Return to Chiang Mai. Note: Participants must be healthy, aged 10-65 years, max weight 110kg, min height 120cm.',
    pricePerPerson: 1900,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Photos and videos', 'Tips for guides'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
    seasonalNote: 'Ultimate Program: 1,900 THB | Extreme Program: 2,500 THB (includes longest 1,200m zipline)',
  },
  {
    id: 'wat-umong-doi-suthep-night',
    title: 'Wat Umong & Doi Suthep at Night',
    description: 'Experience the magical atmosphere of Chiang Mai\'s most sacred temples at sunset and night. Visit the ancient tunnel temple Wat Umong with its unique underground passages and serene forest setting. Then ascend to Doi Suthep Temple to witness the golden pagoda illuminated against the night sky with spectacular city lights below.',
    shortDescription: 'Visit ancient Wat Umong tunnels and Doi Suthep Temple illuminated at night',
    heroImage: '/images/1000016278.webp',
    images: [
      { src: '/images/1000016278.webp', alt: 'Doi Suthep Temple golden pagoda illuminated at night with city lights' },
      { src: '/images/1000016275.webp', alt: 'Doi Suthep Temple golden chedi at twilight with dramatic sky' },
      { src: '/images/1000016281.webp', alt: 'Doi Suthep Temple at dusk overlooking Chiang Mai city' },
      { src: '/images/1000016272.webp', alt: 'Wat Umong ancient tunnel with Buddha statue and candles' },
    ],
    activities: [
      'Wat Umong',
      'Doi Suthep Temple',
    ],
    packageIncludes: [
      'Transportation',
      'Tour Guide',
      'Entrance Ticket',
      'Accident Insurance',
    ],
    pickupTime: '04:40 PM',
    duration: '3-4 hours',
    groupSize: 'Small groups or private',
    difficulty: 'Easy',
    highlights: [
      'Explore ancient Wat Umong underground tunnel temple',
      'Experience serene forest temple atmosphere',
      'Visit Doi Suthep Temple at sunset and night',
      'See the golden pagoda illuminated against night sky',
      'Enjoy spectacular night views of Chiang Mai city lights',
      'Peaceful evening temple experience away from crowds',
    ],
    itinerary: 'Late afternoon pickup from hotel (04:40 PM). Visit Wat Umong to explore the ancient underground tunnels and forest temple grounds. Drive up to Doi Suthep Temple to experience sunset and the golden pagoda illuminated at night. Enjoy spectacular views of Chiang Mai city lights. Return to hotel by evening.',
    pricePerPerson: 650,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Dinner', 'Optional donations'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
  {
    id: 'elephant-jungle-sanctuary-half-day',
    title: 'Elephant Jungle Sanctuary: Half-Day Program',
    description: 'Spend a meaningful half-day with elephants in an ethical environment while learning about their behavior and conservation. Experience personal interaction with elephants in a responsible setting, participate in elephant mud spa treatment, assist with river bathing and cleaning, with photography opportunities throughout the experience.',
    shortDescription: 'Ethical half-day elephant experience with mud spa, river bathing, and conservation education',
    heroImage: '/images/1000016290.webp',
    images: [
      { src: '/images/1000016290.webp', alt: 'Tourists splashing water with elephant during bath time' },
      { src: '/images/1000016288.webp', alt: 'Tourists feeding bananas to elephants at sanctuary' },
      { src: '/images/1000016286.webp', alt: 'Visitors bathing elephant in river' },
      { src: '/images/1000016295.webp', alt: 'Close interaction feeding elephant in natural setting' },
    ],
    activities: [
      'Personal Interaction with Elephants',
      'Educational Session about Elephant Background',
      'Elephant Mud Spa Treatment',
      'River Bathing and Cleaning',
      'Photography Opportunities',
    ],
    packageIncludes: [
      'Food & Drinks',
      'Round-Trip Transfer from Chiang Mai Accommodation',
      'English-Speaking Tour Guide',
      'Lunch',
      'Snacks',
      'Drinking Water',
      'Elephant Food',
    ],
    pickupTime: 'Morning: 06:30-07:00 AM | Afternoon: 11:30-12:00 PM',
    duration: '4-5 hours',
    groupSize: 'Small groups',
    difficulty: 'Easy',
    highlights: [
      'Ethical elephant sanctuary with no riding',
      'Learn about each elephant\'s background and conservation',
      'Feed and interact with elephants in natural environment',
      'Participate in mud spa treatment for elephants',
      'Help bathe and clean elephants in river',
      'Photography opportunities throughout experience',
      'Support elephant welfare and conservation',
    ],
    itinerary: 'Pickup from hotel at selected time (morning or afternoon session). Transfer to Elephant Jungle Sanctuary. Meet elephants and learn about their stories. Feed elephants and participate in mud spa treatment. Walk with elephants to river for bathing and cleaning. Enjoy lunch/snacks. Photography session. Return to Chiang Mai.',
    pricePerPerson: 1900,
    currency: 'THB',
    packageExcludes: ['Personal expenses', 'Tips for guides', 'Photos and videos (available for purchase)'],
    paymentTerms: '50% deposit required to confirm booking, balance due 3 days before tour',
    cancellationPolicy: 'Free cancellation up to 7 days before tour. 50% refund for 3-7 days. No refund within 3 days.',
  },
];

export function getTourById(id: string): Tour | undefined {
  return tours.find(tour => tour.id === id);
}

export function getAllTours(): Tour[] {
  return tours;
}
